In [274]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print("PyTorch version:", torch.__version__)

PyTorch version: 2.11.0


## Intro to Tensors

### Creating Tensors

In [275]:
# scalar
scalar = torch.tensor(3)
scalar

tensor(3)

In [276]:
# but I wanted that number '3' not like 'tensor(3)'

scalar.item()  # .item() method to get the python number from a tensor containing a single value

3

In [277]:
# dim of an scalar
scalar.ndim

0

In [278]:
print(f"Hence an Scalar has {scalar.ndim} dimension.")

Hence an Scalar has 0 dimension.


In [279]:
#  vector

vector = torch.tensor([11, 14, 1])
vector

tensor([11, 14,  1])

In [280]:
# Again i wanted that number '11' and '2' not like 'tensor([11,  2])'

ls = vector.tolist()  # .tolist() method to get the python list from a tensor containing multiple values
print(f"Vector as list: {ls}")
# or 

np_array = vector.numpy()  # .numpy() method to get the numpy array from a tensor containing multiple values
print(f"Vector as numpy array: {np_array}, Array contains no comma.")

# or

vector[0].item()  # .item() method to get the python number from a tensor containing a single value
vector[1].item()  # .item() method to get the python number from a tensor containing a single value


Vector as list: [11, 14, 1]
Vector as numpy array: [11 14  1], Array contains no comma.


14

In [281]:
for i in range(len(vector)):
    print(vector[i].item())

11
14
1


In [282]:
# one thing to see
vector.ndim

1

In [283]:
print(f"Hence a Vector has {vector.ndim} dimension.")

Hence a Vector has 1 dimension.


**Well those Square Bracket counts specify the number of the dim**

In [284]:
# BUT
print(f"Vector shape: {vector.shape}")
# number of elements in the vector
print(f"Number of elements in the vector: {vector.numel()}")


Vector shape: torch.Size([3])
Number of elements in the vector: 3


In [285]:
# MATRIX

MATRIX = torch.tensor([[-2, -1, 0],
                       [1, 2, 3],
                       [4, 5, 6]])

MATRIX

tensor([[-2, -1,  0],
        [ 1,  2,  3],
        [ 4,  5,  6]])

In [286]:
print(f"Hence a Matrix:\n {MATRIX.numpy()}")

Hence a Matrix:
 [[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]


In [287]:
MATRIX.ndim

2

In [288]:
MATRIX.shape

torch.Size([3, 3])

In [289]:
MATRIX[1]

tensor([1, 2, 3])

In [290]:
# Tensor

TENSOR = torch.tensor([[[1, 2, 3,],
                        [4, 5, 6],
                        [7, 8, 9],
                        [7, 8, 9]],
                            [[10, 11, 12],
                            [13, 14, 15],
                            [16, 17, 18],
                            [7, 8, 9]],
                                [[19, 20, 21],
                                [22, 23, 24],
                                [25, 26, 27],
                                [7, 8, 9]]])    

In [291]:
TENSOR.numpy()


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [ 7,  8,  9]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [ 7,  8,  9]]])

In [292]:
TENSOR.ndim

3

In [293]:
TENSOR.shape

torch.Size([3, 4, 3])

In [294]:
TENSOR[0] # dim = 0

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [7, 8, 9]])

In [295]:
TENSOR[0][0] # dim = 1

tensor([1, 2, 3])

In [296]:
TENSOR[0][0][0] # dim = 2

tensor(1)

### Random Tensors !

In [297]:
# Create random tensor of size (3, 4)
# random_tensor = torch.rand(size=(3, 4), dtype=torch.float32, requires_grad=True, generator=torch.manual_seed(42), out=None, layout=torch.strided, device=None, pin_memory=False, )  # set random seed for reproducibility

random_tensor = torch.rand(size=(3, 4))  # set random seed for reproducibility
random_tensor

tensor([[0.3381, 0.3357, 0.5472, 0.8406],
        [0.8410, 0.3132, 0.9098, 0.3988],
        [0.8320, 0.8297, 0.9768, 0.9518]])

In [298]:
random_tensor.ndim

2

In [299]:
# similar to image size tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3))  # H, W, C (height, width, color channels)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeroes and Ones

In [300]:
zeros = torch.zeros((3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [301]:
ones = torch.ones((3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [302]:
ones.dtype # default dtype is float32

torch.float32

### Creating a range of tensors and tensors-like

In [303]:
one_to_ten = torch.arange(start = 1, end = 11, step = 1.5)
one_to_ten
# returns 1-D range of numbers from  ceil((end-start)/step) 
# Step is added to the start value until it reaches the end

tensor([ 1.0000,  2.5000,  4.0000,  5.5000,  7.0000,  8.5000, 10.0000])

In [304]:
np.ceil((11-1)/1.5)

7.0

In [305]:
one_to_ten.size()

torch.Size([7])

In [306]:
# tensor - like

ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros


tensor([0., 0., 0., 0., 0., 0., 0.])

In [307]:
ten_ones = torch.ones_like(input = one_to_ten)
ten_ones

tensor([1., 1., 1., 1., 1., 1., 1.])

### Tensor data types

In [308]:
# float 32 tensor
float_32_tensor = torch.tensor([1.0, 2.0, 3.0],
                               dtype=None,
                               device=None,
                               requires_grad=False 
# requires_grad is used to track the gradients of the tensor during backpropagation
                               )
float_32_tensor.dtype


torch.float32

In [309]:
float_16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

Conversion

In [310]:
# or
new_float_16_tensor = float_32_tensor.type(torch.float16)
new_float_16_tensor.dtype

torch.float16

OR

In [311]:
new2_float_16_tensor = float_32_tensor.to(torch.float16)
new2_float_16_tensor.dtype

torch.float16

In [312]:
float_64_tensor = torch.tensor([111.0, 222.0, 333.0], dtype=torch.float64)

In [313]:
n = (float_16_tensor * float_32_tensor * float_64_tensor)

In [314]:
n.dtype

torch.float64

### Some tensor

In [315]:
some_tensor = torch.rand(3,3)
some_tensor 

tensor([[0.7318, 0.8822, 0.1317],
        [0.2771, 0.6802, 0.2342],
        [0.7923, 0.8053, 0.3294]])

In [316]:
print(f"some_tensor: \n{some_tensor},\ndtype: {some_tensor.dtype},\nshape: {some_tensor.shape},\nndim: {some_tensor.ndim},\ndevice: {some_tensor.device}")

some_tensor: 
tensor([[0.7318, 0.8822, 0.1317],
        [0.2771, 0.6802, 0.2342],
        [0.7923, 0.8053, 0.3294]]),
dtype: torch.float32,
shape: torch.Size([3, 3]),
ndim: 2,
device: cpu


### Tensor Operations

#### Elementwise

In [317]:
tensor = torch.tensor([1, 2, 3])

In [318]:
tensor + 10

tensor([11, 12, 13])

In [319]:
tensor - 1

tensor([0, 1, 2])

In [320]:
tensor * 10

tensor([10, 20, 30])

In [321]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

OR

In [322]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [323]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [324]:
torch.sub(tensor, 1)

tensor([0, 1, 2])

In [325]:
torch.div(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

#### Matrix Multiplication

In [326]:
print("Element-wise multiplication:\n",tensor, "*", tensor, "=", tensor * tensor)

Element-wise multiplication:
 tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [327]:
print("matrix multiplication:\n",tensor, "@", tensor, "=", tensor @ tensor)

matrix multiplication:
 tensor([1, 2, 3]) @ tensor([1, 2, 3]) = tensor(14)


or

In [328]:
print("matrix multiplication:\n",tensor, "@", tensor, "=", torch.matmul(tensor, tensor))

matrix multiplication:
 tensor([1, 2, 3]) @ tensor([1, 2, 3]) = tensor(14)


#### Difference between these

In [329]:
%%time

value = 0

for i in range(len(tensor)):
    value += tensor[i] * tensor[i]


CPU times: user 172 μs, sys: 179 μs, total: 351 μs
Wall time: 193 μs


In [330]:
%%time
tensor @ tensor


CPU times: user 31 μs, sys: 5 μs, total: 36 μs
Wall time: 37 μs


tensor(14)

In [331]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 26 μs, sys: 2 μs, total: 28 μs
Wall time: 29.1 μs


tensor(14)

`matmul()` 29.1 μs < `@` 37 μs < `for loop` 193 μs